language: node_js
node_js: 12
mono:
  - latest

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode10

env:
  global:
    - secure: "hufOrXezWqmB7S0wWiXJiaNszssObfSavvc3tOMLEey1yLZbDqo6Teck/5juYa6OQBVFKFeXgs6H0W/HfDb8NOHrCzIndhhpT5hSSyazif/YRsHUWyhYmg4P8KYm/YEh/dkNXvxp8P/485bNOU4ocIrWtgAF90c0/07g0SDq2zZmwdgb5Ye7DF99fBMk1u0doDYTpHqFNEtj+bvEh6AQXfwsrr1c+tqrAeetkiCrAYQlP9aDZ0MR3GoAvdNQiCrr5/PuJxsudcaTgjL5WlSw0sT8cl1b29euqoSM7LYieAi4rgGK4pSQrp7Psr+d3gwZ+w5fcJudWg8M2nNMlKdtfXU7iLzqBVQ1Wae+39835hxtx4ick2EOixhSOdEmrx34XCVBL5yk4pNYs1vrK+NnhlQ6gf8KS/cGnSbnkcz+W77i5Q1DNs4RSDw5IDYssekEfz9kHpKJL0sAGY6IlIKmm/FCrR/ByGMVd5ho2obeF716q5DOKbEDtDVsb4S5LbAga/CyLXvL4eAIjVrghLI97wFPZlCuWnrveeX2+VQkYQoLomD2oG9Iahu0o65XkSikbPXc+3VKuCnxJ2epLN14XdwcgP4THn3UmzKZ7Sepac9Xj224945zCeXpk5TRBydD2LW63WjhvINJvp5G5aLXxRuv5z2EhOtq9NVImQSzpOw="
    - CSC_IDENTITY_AUTO_DISCOVERY=false
    - YARN_GPG=no # otherwise Yarn starts a GPG daemon which prevents builds from finishing on Windows

cache:
  yarn: true
  directories:
    - "node_modules"
    - "packages/core/node_modules"
    - "packages/desktop/node_modules"
    - "packages/erc20/node_modules"
    - "packages/services/node_modules"
    - "packages/ui/node_modules"

# Need for gitversion
git:
  depth: false

before_install:
  # GitVersion
  - echo Installing GitVersion...
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install mono; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install curl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export GITVERSION_NAME="gitversion-ubuntu.18.04-x64-5.3.3.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export GITVERSION_NAME="gitversion-osx-x64-5.3.3.tar.gz"; fi

  # wget https://github.com/GitTools/GitVersion/releases/download/v4.0.0/GitVersion-bin-net40-v4.0.0.zip
  - wget https://github.com/GitTools/GitVersion/releases/download/5.3.3/$GITVERSION_NAME
  # unzip GitVersion-bin-net40-v4.0.0.zip -d GitVersionBin
  - mkdir GitVersionBin
  - tar -zxvf $GITVERSION_NAME -C GitVersionBin
  - echo "#!/bin/bash" > gitversion
  - echo 'GitVersionBin/gitversion "$@"' >> gitversion
  - chmod 755 gitversion
  - ./gitversion /version
  # Janus
  - echo Janus...
  - curl -sL https://raw.githubusercontent.com/ETCDEVTeam/janus/master/get.sh | bash
  - export PATH=$PATH:$PWD/janusbin
  # Warm up Yarn
  - echo Installing dependencies
  - npm install -g node-gyp license-checker
  - npm install -g codecov yarn lerna
  - npm install -g typescript

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn install

before_script:
  - tsc -V
  - ./gitversion

script:
  - ./gitversion > packages/desktop/gitversion.json
  - export APP_VERSION_GIT_TAG="$(./gitversion /showvariable FullSemVer)-$(./gitversion /showvariable ShortSha)"
  - echo "Building app version $APP_VERSION_GIT_TAG"
  - if [[ $(license-checker --production --exclude '(GPL-2.0 OR MIT)' | grep GPL) ]]; then license-checker --production | grep -C 1 GPL && false; fi
  - yarn build
  - yarn test:coverage
  # - yarn lint:ts
  - travis_wait 30 yarn build:dist
after_success:
  # Show dist directory contents after a successful build.
  - ls -l ./packages/desktop/dist/
  # Set up GCP deployment
  # to encrypt:
  # openssl aes-256-cbc -e -in gcloud-plain.json -k $GCP_PASSWD -out gcloud-travis.json.enc -md sha256
  - openssl aes-256-cbc -d -in gcloud-travis.json.enc -k $GCP_PASSWD -out .gcloud.json -md sha256

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - build-essential
    - libudev-dev
    - libusb-1.0-0
    - libusb-1.0-0-dev
    - mono-complete
    - libcurl3
    - xvfb
deploy:
  - provider: script
    script: ./gcloud-deploy.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: ./gcloud-deploy.sh
    skip_cleanup: true
    on:
      tags: true
