= Nicowin92 Wallet for Desktop

Features:

- *Windows, macOS and Linux*
- *Ethereum, Ethereum Classic, Tether and Dai*
- Imports Private Key from JSON or Raw Hex
- Supports Mnemonic Phrase (*BIP-39*) and HD Accounts (*BIP-32*)
- Supports *Hardware Wallets*, Ledger Nano S and Nano X
- Doesn't require a local full node

== Development instructions

=== Code Design

The project is based on

- Electron + NodeJS
- Typescript
- React + Redux
- Rust for some modules

Once nodenv is installed:

----
$ nodenv install
----

The required version of `node` >= `v12`.

=== Dependencies

==== Libs

You need `libudev`, `libusb-1.0-0`, `libusb-1.0-0-dev` installed on Linux

.On Ubuntu:
----
sudo apt-get install libudev-dev libusb-1.0-0 libusb-1.0-0-dev
----

====  NPM packages


.Install development tools
----
npm install -g node-gyp lerna yarn
----

.For windows run also:
----
npm install -g npm windows-build-tools@4.0.0
----

.Install dependencies:
----
lerna bootstrap
----

=== Run for development

.Build sources
----
$ lerna run build
----

.Start Electron application
----
$ lerna run start:electron
----

=== Logs

Electron and Nicowin92 logs persisted in:

 * OSX: `~/Library/Logs/Nicowin92Wallet/log.log`
 * Linux: `~/.config/Nicowin92Wallet/log.log`

=== Building distributions in development

You can run a distribution build in your development environment. Assuming
you've already compiled `./src/` and `./electron/`, you'll be able to run:

----
yarn build:dist
----

This command will build for _your current system_. Note that there are configurations for
several systems (OSX, Linux, Windows) specified in the `"build"` field of `package.json`, but the `dist` command will by default only build for the system it's on.

Note: If you're developing on OSX and have a developer signing identity on your machine, you can
optionally disable that with `CSC_IDENTITY_AUTO_DISCOVERY=false`.

OSX is also able to build for Linux. Add `-ml` to that raw command to build for
both OSX and Linux at the same time.

=== Troubleshooting
Some preliminary things to try in case you run into issues:

Clear out any persisted settings or userdata from previous trials
 * OSX: `~/Library/Application Support/Nicowin92Wallet`
 * Linux: `~/.config/Nicowin92Wallet`
 * Windows: `%APPDATA%\Nicowin92Wallet`

== Run tests

----
yarn test:watch
----

or for single run:
----
yarn test
----

== License

Copyright 2020 Nicowin92Pay, Inc

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
